### ISSUE TITLE
Example of exporting sheet to pdf

### ISSUE THREAD

**Issue by davidlam-at-home** [devlights/goxcel#60]
Hi @devlights your work look very useful.  Would you be interested in creating an example for exporting a sheet to a pdf file?

Currently I am using python, similar to what is in
https://www.geeksforgeeks.org/convert-excel-to-pdf-using-python/

But I don't usually use python.  It would be neater to do everything in go. 

Thanks for reading.

**Comment by devlights** [comment]
Hi. Thanks for your comment. I'll try to prepare an API when I have time. In the meantime, I'll create an issue. 😃

**Comment by davidlam-at-home** [comment]
Thanks @devlights you're the best!!  👍

**Comment by devlights** [comment]
@davidlam-at-home Here it is. (#62 )

https://github.com/devlights/goxcel/blob/master/examples/export_pdf/export_pdf.go

**Comment by davidlam-at-home** [comment]
Thanks again @devlights this works better than my python version.  The python version sometimes gets stuck when there is an existing excel.exe running, and this one doesn't have the problem.
